import api from './api';

// Curated Northern Vietnam destinations dataset with full authentic local places
export const CURATED_NORTHERN_DESTINATIONS = [
  {
    id: 1,
    slug: 'ta-xua',
    name: 'Tà Xùa - Thiên Đường Mây Bắc Yên',
    region: 'Sơn La',
    description: 'Xã vùng cao thuộc Bắc Yên, Sơn La, nổi tiếng với biển mây cuồn cuộn ngập tràn thung lũng, Sống lưng khủng long Háng Đồng, Mỏm Cá Heo và Đỉnh Gió.',
    cover_image: '/images/taxua.jpg',
    best_months: 'Tháng 10 - Tháng 4',
    difficulty: 'Trung bình',
    how_to_get_there: 'Xe khách giường nằm từ bến Mỹ Đình/Yên Nghĩa lên Bắc Yên (~250k), sau đó thuê xe máy hoặc xe ôm bản địa lên đỉnh Tà Xùa.',
    warnings: 'Đường dốc sương mù dày lúc 5h sáng. Nên chọn xe số hoặc côn tay, kiểm tra phanh cẩn thận trước khi đổ đèo.',
    avg_budget: '1.200.000 - 1.800.000 VNĐ / người',
    is_featured: true,
    elevation: '2.865m',
    cloud_chance: '95%',
    places: [
      {
        id: 101,
        name: 'Homestay A Phù Tà Xùa',
        category: 'stay',
        category_name: 'Homestay Bản Địa',
        category_icon: '🏨',
        rating: 4.9,
        review_count: '320+',
        location_tag: 'Bản Chống Tra',
        highlight_tag: 'View mây 360°',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'View ôm trọn biển mây từ giường ngủ qua cửa sổ tràn kính. Nổi danh với lẩu gà đen than hoa Tây Bắc thơm lừng và hiên gỗ ngắm bình minh.',
        price_label: 'Mức giá lưu trú',
        price_value: '250k - 650k /đêm',
        cta_text: 'Chi tiết →',
        contact_phone: '0987 654 321'
      },
      {
        id: 102,
        name: 'Tiệm Cà Phê Mị Ơi',
        category: 'cafe',
        category_name: 'Cà phê ngắm cảnh',
        category_icon: '☕',
        rating: 4.8,
        review_count: '510+',
        location_tag: 'Đỉnh Gió',
        highlight_tag: 'Hoàng hôn đỏ rực',
        image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
        description: 'Góc ngắm hoàng hôn đỏ rực thung lũng Bản Mù đẹp bậc nhất Tà Xùa. Nổi bật với thức uống nước mơ má đào ủ đường phèn và trà táo mèo ấm nồng.',
        price_label: 'Menu đồ uống',
        price_value: '40k - 60k /món',
        cta_text: 'Đường đi 🗺️',
        contact_phone: '0912 345 678'
      },
      {
        id: 103,
        name: 'Camp & Glamping Mỏm Cá Heo',
        category: 'stay',
        category_name: 'Glamping Sinh Tồn',
        category_icon: '⛺',
        rating: 4.7,
        review_count: '180+',
        location_tag: 'Mỏm Cá Heo',
        highlight_tag: 'Lửa trại đêm',
        image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
        description: 'Lều bạt dã ngoại chịu gió bão cấp độ cao, trang bị túi ngủ ấm 5°C. Buổi tối đốt lửa trại, nướng khoai mật thơm nức và ngắm ngân hà.',
        price_label: 'Gói cắm trại trọn gói',
        price_value: '350k /người',
        cta_text: 'Đặt lều ⛺',
        contact_phone: '0966 888 999'
      },
      {
        id: 104,
        name: 'Quán Ăn Dân Tộc A Lử',
        category: 'eat',
        category_name: 'Đặc Sản Tây Bắc',
        category_icon: '🍲',
        rating: 4.9,
        review_count: '440+',
        location_tag: 'Trung tâm Tà Xùa',
        highlight_tag: 'Món bản địa',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        description: 'Địa chỉ ẩm thực nức tiếng của dân phượt: Gà đen H\'Mông thả đồi thịt săn ngọt, thịt trâu gác bếp chấm chẳm chéo thơm lừng hạt dổi mắc khén.',
        price_label: 'Chi phí bình quân',
        price_value: '~120k /người/bữa',
        cta_text: 'Xem Menu 📖',
        contact_phone: '0977 123 456'
      },
      {
        id: 105,
        name: 'Rừng chè Shan Tuyết Bản Bẹ',
        category: 'checkin',
        category_name: 'Văn Hóa Bản Địa',
        category_icon: '🍃',
        rating: 4.8,
        review_count: '196+',
        location_tag: 'Rừng Cổ Thụ Bản Bẹ',
        highlight_tag: '300+ năm tuổi',
        image: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80',
        description: 'Trải nghiệm sao chè củi thủ công cùng nghệ nhân người Mông, hái búp chè trắng phủ tuyết trên thân cây cổ thụ rêu phong sương mù.',
        price_label: 'Vé tham quan & thử chè',
        price_value: '50k /vé',
        cta_text: 'Đăng ký 🍃',
        contact_phone: '0934 567 890'
      },
      {
        id: 106,
        name: 'Mỏm Lạc Đà & Cây Cô Đơn Tà Xùa',
        category: 'checkin',
        category_name: 'Tọa Độ Check-in',
        category_icon: '📸',
        rating: 4.9,
        review_count: '680+',
        location_tag: 'Hướng Tây Bắc',
        highlight_tag: 'Bình minh & Hoàng hôn',
        image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        description: 'Vách đá nhô ra giữa không trung tạo góc chụp ngoạn mục tựa lưng vào lưng lạc đà. Nơi ngắm bình minh ráng vàng vờn biển mây tuyệt mỹ.',
        price_label: 'Phí vào cửa',
        price_value: 'Miễn phí (Bảo vệ MT)',
        cta_text: 'Định vị Map 🧭',
        contact_phone: 'Bản địa'
      },
      {
        id: 107,
        name: 'Trekking Sống Lưng Khủng Long Háng Đồng',
        category: 'trekking',
        category_name: 'Hoạt Động & Trekking',
        category_icon: '🥾',
        rating: 4.9,
        review_count: '1.200+',
        location_tag: 'Xã Háng Đồng',
        highlight_tag: 'Săn mây 360°',
        image: '/images/taxua.jpg',
        description: 'Chinh phục sống núi hẹp tựa lưng khủng long khổng lồ chìm trong đại dương mây trắng cuộn trào hai bên sườn núi.',
        price_label: 'Xe ôm bản địa',
        price_value: '60k - 80k /khứ hồi',
        cta_text: 'Lộ trình Trekking 🥾',
        contact_phone: '0988 123 789'
      },
      {
        id: 108,
        name: 'Xe Khách Giường Nằm Toàn Điệp',
        category: 'transport',
        category_name: 'Cách Di Chuyển',
        category_icon: '🚌',
        rating: 4.7,
        review_count: '310+',
        location_tag: 'Bến Mỹ Đình - Bắc Yên',
        highlight_tag: 'Xe đêm 21h30',
        image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
        description: 'Tuyến xe giường nằm êm ái xuất phát mỗi đêm từ bến xe Mỹ Đình lên thẳng thị trấn Bắc Yên và hỗ trợ xe trung chuyển lên Tà Xùa.',
        price_label: 'Giá vé một chiều',
        price_value: '250k - 300k /vé',
        cta_text: 'Đặt vé xe 🎫',
        contact_phone: '0913 222 333'
      }
    ]
  },
  {
    id: 2,
    slug: 'ha-giang',
    name: 'Hà Giang - Mã Pí Lèng, Hẻm Tu Sản & Sông Nho Quế',
    region: 'Hà Giang',
    description: 'Vùng đất địa đầu Tổ quốc với cao nguyên đá Đồng Văn kỳ vĩ, hẻm Tu Sản sâu nhất Đông Nam Á và dòng sông Nho Quế màu ngọc bích uốn lượn dưới chân đèo Mã Pí Lèng.',
    cover_image: '/images/destination_banner.png',
    best_months: 'Tháng 9 - Tháng 12',
    difficulty: 'Trung bình',
    how_to_get_there: 'Xe Limousine Hà Nội - TP Hà Giang (~300k). Thuê xe máy chạy cung đèo Quản Bạ - Yên Minh - Đồng Văn - Mèo Vạc.',
    warnings: 'Nhiều khúc cua tay áo và vực sâu. Chú ý giữ tốc độ an toàn khi đổ dốc đèo Mã Pí Lèng.',
    avg_budget: '2.500.000 - 3.500.000 VNĐ / người',
    is_featured: true,
    elevation: '1.800m',
    cloud_chance: '88%',
    places: [
      {
        id: 201,
        name: 'Bến Thuyền Hẻm Tu Sản & Chèo SUP Nho Quế',
        category: 'trekking',
        category_name: 'Trải Nghiệm Sông Nước',
        category_icon: '🚣',
        rating: 4.9,
        review_count: '880+',
        location_tag: 'Bến thuyền Tà Làng',
        highlight_tag: 'Hẻm sâu 800m',
        image: '/images/destination_banner.png',
        description: 'Du thuyền lướt đi giữa lòng sông Nho Quế màu ngọc bích phẳng lặng, hai bên là vách núi đá dựng đứng kỳ vĩ nhất Đông Nam Á.',
        price_label: 'Vé thuyền & SUP',
        price_value: '120k - 150k /người',
        cta_text: 'Đặt thuyền 🚤',
        contact_phone: '0978 123 456'
      },
      {
        id: 202,
        name: 'Mã Pí Lèng Panorama Coffee',
        category: 'cafe',
        category_name: 'Cà phê ngắm cảnh',
        category_icon: '☕',
        rating: 4.8,
        review_count: '640+',
        location_tag: 'Đèo Mã Pí Lèng',
        highlight_tag: 'View vực Tu Sản',
        image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
        description: 'Góc uống cafe trên vách đá ngắm trọn vẹn toàn cảnh sông Nho Quế uốn lượn và khúc cua chữ M huyền thoại của cung đèo hạnh phúc.',
        price_label: 'Đồ uống & Trà hoa',
        price_value: '45k - 70k /món',
        cta_text: 'Đường đi 🗺️',
        contact_phone: '0966 222 111'
      },
      {
        id: 203,
        name: 'Homestay Chúng Pủa (Auberge de Meo Vac)',
        category: 'stay',
        category_name: 'Di Sản Bản Địa',
        category_icon: '🏨',
        rating: 4.9,
        review_count: '210+',
        location_tag: 'Thị trấn Mèo Vạc',
        highlight_tag: 'Nhà cổ 100 năm',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'Ngôi nhà trình tường bằng đất lợp ngói âm dương tuổi đời hơn một thế kỷ của người H\'Mông, phục vụ rượu ngô men lá và lẩu dê thơm ngon.',
        price_label: 'Giá phòng lưu trú',
        price_value: '350k - 950k /đêm',
        cta_text: 'Chi tiết →',
        contact_phone: '0983 555 777'
      },
      {
        id: 204,
        name: 'Quán Thắng Cố & Phở Chua Bà Hà',
        category: 'eat',
        category_name: 'Đặc Sản Phố Cổ',
        category_icon: '🍲',
        rating: 4.8,
        review_count: '490+',
        location_tag: 'Phố Cổ Đồng Văn',
        highlight_tag: 'Ẩm thực gia truyền',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        description: 'Nồi thắng cố ngựa nghi ngút khói thơm phức mùi thảo quả quế hồi, ăn kèm bánh phở chua thanh mát và chén rượu ngô cay nồng ấm lòng.',
        price_label: 'Mức giá món',
        price_value: '40k - 100k /món',
        cta_text: 'Xem Menu 📖',
        contact_phone: '0912 888 666'
      },
      {
        id: 205,
        name: 'Cột Cờ Lũng Cú & Cafe Cực Bắc',
        category: 'checkin',
        category_name: 'Tọa Độ Thiêng Liêng',
        category_icon: '📸',
        rating: 4.9,
        review_count: '920+',
        location_tag: 'Lô Lô Chải, Lũng Cú',
        highlight_tag: 'Điểm Cực Bắc',
        image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        description: 'Chạm tay vào lá cờ đỏ sao vàng 54m² trên đỉnh núi Rồng, sau đó ghé bản Lô Lô Chải nhâm nhi ly cafe trong nhà nấm cổ kính.',
        price_label: 'Vé tham quan',
        price_value: '25k /vé',
        cta_text: 'Định vị Map 🧭',
        contact_phone: '0979 333 444'
      },
      {
        id: 206,
        name: 'Dinh Thự Họ Vương (Vua Mèo)',
        category: 'checkin',
        category_name: 'Di Tích Lịch Sử',
        category_icon: '🏛️',
        rating: 4.8,
        review_count: '450+',
        location_tag: 'Sà Phìn, Đồng Văn',
        highlight_tag: 'Kiến trúc đá & gỗ',
        image: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80',
        description: 'Khu dinh thự bề thế bằng gỗ pơ-mu và đá xanh của thủ lĩnh H\'Mông Vương Chính Đức, ẩn chứa những câu chuyện lịch sử huyền bí.',
        price_label: 'Vé vào cổng',
        price_value: '20k /vé',
        cta_text: 'Khám phá 🏛️',
        contact_phone: 'Ban quản lý'
      },
      {
        id: 207,
        name: 'Bản Lô Lô Chải Homestay',
        category: 'stay',
        category_name: 'Không Gian Bản Địa',
        category_icon: '🏨',
        rating: 4.9,
        review_count: '350+',
        location_tag: 'Dưới chân Cột Cờ',
        highlight_tag: 'Nhà nấm cổ tích',
        image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
        description: 'Nghỉ đêm giữa ngôi làng cổ tích của người Lô Lô hoa, ngắm hoa tam giác mạch trước hiên nhà và thưởng thức cơm lam thịt gác bếp.',
        price_label: 'Giá phòng lưu trú',
        price_value: '300k - 700k /đêm',
        cta_text: 'Đặt phòng ⛺',
        contact_phone: '0968 111 222'
      },
      {
        id: 208,
        name: 'Thuê Xe Máy Phượt Giang Sơn Hà Giang',
        category: 'transport',
        category_name: 'Dịch Vụ Xe Máy',
        category_icon: '🛵',
        rating: 4.9,
        review_count: '1.200+',
        location_tag: 'TP Hà Giang',
        highlight_tag: 'Giao xe tận bến',
        image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80',
        description: 'Dịch vụ thuê xe máy Honda Wave, Blade, XR150 chuyên đổ đèo chất lượng cao, trang bị sẵn áo mưa, giáp bảo hộ và bản đồ phượt.',
        price_label: 'Giá thuê xe',
        price_value: '150k - 250k /ngày',
        cta_text: 'Liên hệ thuê 📞',
        contact_phone: '0988 999 888'
      }
    ]
  },
  {
    id: 3,
    slug: 'moc-chau',
    name: 'Mộc Châu - Cao Nguyên Xanh & Thung Lũng Mận Nà Ka',
    region: 'Sơn La',
    description: 'Nổi tiếng với những đồi chè trái tim bát ngát, thung lũng mận Nà Ka mùa hoa trắng muốt, rừng thông Bản Áng thơ mộng và thác Dải Yếm hùng vĩ giữa cao nguyên lộng gió.',
    cover_image: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=1200&q=80',
    best_months: 'Tháng 1 - Tháng 5 & Tháng 9 - 11',
    difficulty: 'Dễ',
    how_to_get_there: 'Xe khách hoặc Limousine từ Hà Nội theo QL6 qua đèo Thung Khe (khoảng 4 - 5 tiếng di chuyển).',
    warnings: 'Mùa hoa mận đông du khách cuối tuần, nên đặt phòng homestay trước ít nhất 1-2 tuần.',
    avg_budget: '1.200.000 - 1.800.000 VNĐ / người',
    is_featured: true,
    elevation: '1.050m',
    cloud_chance: '78%',
    places: [
      {
        id: 301,
        name: 'Thung Lũng Mận Nà Ka',
        category: 'checkin',
        category_name: 'Check-in Mùa Hoa',
        category_icon: '🌸',
        rating: 4.9,
        review_count: '780+',
        location_tag: 'Pa Khen, Mộc Châu',
        highlight_tag: 'Hoa trắng & Quả chín',
        image: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80',
        description: 'Thung lũng mận rộng hơn 100 hecta, nở trắng muốt tựa tuyết rơi vào mùa xuân và trĩu quả đỏ mọng ngọt lịm vào mùa hè.',
        price_label: 'Vé vào vườn mận',
        price_value: '30k - 50k /người',
        cta_text: 'Định vị Map 🧭',
        contact_phone: '0975 666 888'
      },
      {
        id: 302,
        name: 'Nhà Hàng Bê Chao 64 Mộc Châu',
        category: 'eat',
        category_name: 'Đặc Sản Cao Nguyên',
        category_icon: '🍲',
        rating: 4.8,
        review_count: '850+',
        location_tag: 'Tiểu khu Chiềng Đi',
        highlight_tag: 'Bê chao giòn rụm',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        description: 'Quán ăn lừng danh với món bê chao dầu sôi thơm lừng, bì giòn thịt mềm ngọt chấm tương gừng, kèm rau cải mèo xào tỏi và cơm nếp nương.',
        price_label: 'Chi phí món ăn',
        price_value: '100k - 200k /người',
        cta_text: 'Xem Menu 📖',
        contact_phone: '0969 888 777'
      },
      {
        id: 303,
        name: 'Tiệm Cà Phê Đồi Gió Mộc Châu',
        category: 'cafe',
        category_name: 'Cà Phê Sunset',
        category_icon: '☕',
        rating: 4.8,
        review_count: '430+',
        location_tag: 'Đồi Gió Mộc Châu',
        highlight_tag: 'Hoàng hôn thung lũng',
        image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
        description: 'Quán cà phê gỗ view 360 độ ngắm toàn cảnh thung lũng mận và những đồi chè bát ngát khi chiều tà buông nắng vàng dịu nhẹ.',
        price_label: 'Đồ uống & Trà sữa',
        price_value: '35k - 55k /món',
        cta_text: 'Đường đi 🗺️',
        contact_phone: '0915 222 444'
      },
      {
        id: 304,
        name: 'The Nordic Village Mộc Châu',
        category: 'stay',
        category_name: 'Resort Bắc Âu',
        category_icon: '🏨',
        rating: 4.9,
        review_count: '310+',
        location_tag: 'Bản Húa Tạt, Vân Hồ',
        highlight_tag: 'Rừng thông nguyên sinh',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'Khu villa gỗ phong cách Bắc Âu ẩn mình giữa rừng thông bạt ngàn, phòng có bồn tắm đá khoáng nóng và lò sưởi củi ấm cúng.',
        price_label: 'Giá phòng biệt thự',
        price_value: '1.200k - 2.500k /đêm',
        cta_text: 'Chi tiết →',
        contact_phone: '0981 333 555'
      },
      {
        id: 305,
        name: 'Đồi Chè Trái Tim Tân Lập',
        category: 'checkin',
        category_name: 'Biểu Tượng Xanh',
        category_icon: '🍃',
        rating: 4.8,
        review_count: '910+',
        location_tag: 'Xã Tân Lập',
        highlight_tag: 'Sống ảo triệu view',
        image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
        description: 'Đồi chè ô long xanh ngút ngàn được uốn thành hình trái tim độc đáo, không khí thơm mùi búp trà tươi non tinh khôi buổi sớm mai.',
        price_label: 'Vé tham quan',
        price_value: 'Miễn phí',
        cta_text: 'Khám phá 🍃',
        contact_phone: '0972 111 444'
      },
      {
        id: 306,
        name: 'Rừng Thông Bản Áng & Chimi Farm',
        category: 'stay',
        category_name: 'Cắm Trại & Hái Dâu',
        category_icon: '⛺',
        rating: 4.7,
        review_count: '620+',
        location_tag: 'Đông Sang, Mộc Châu',
        highlight_tag: 'Dâu tây hữu cơ',
        image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
        description: 'Hồ nước thơ mộng bên rừng thông reo rì rào, tự tay hái những quả dâu tây Chimi căng mọng và cắm trại BBQ ngắm sao đêm.',
        price_label: 'Vé vào cổng',
        price_value: '50k - 80k /vé',
        cta_text: 'Đặt lều ⛺',
        contact_phone: '0984 777 999'
      },
      {
        id: 307,
        name: 'Thác Dải Yếm & Cầu Kính Tình Yêu',
        category: 'checkin',
        category_name: 'Thác Nước Kỳ Vĩ',
        category_icon: '💦',
        rating: 4.7,
        review_count: '540+',
        location_tag: 'Mường Sang',
        highlight_tag: 'Cầu kính 5D',
        image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
        description: 'Ngọn thác 9 tầng đổ nước trắng xóa mềm mại như dải yếm lụa của thiếu nữ Thái, kèm cầu kính công nghệ 5D đầu tiên tại Việt Nam.',
        price_label: 'Vé cầu kính & thác',
        price_value: '100k /vé',
        cta_text: 'Định vị Map 🧭',
        contact_phone: 'Ban quản lý'
      },
      {
        id: 308,
        name: 'Nhà Xe Limousine Xuân Tráng Mộc Châu',
        category: 'transport',
        category_name: 'Xe Đón Tận Nơi',
        category_icon: '🚌',
        rating: 4.8,
        review_count: '950+',
        location_tag: 'Hà Nội - Mộc Châu',
        highlight_tag: 'Ghế VIP massage',
        image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
        description: 'Hãng xe Limousine 9 chỗ ghế thương gia đưa đón tận nhà tại Hà Nội lên thẳng các homestay trung tâm Mộc Châu mỗi 1 tiếng/chuyến.',
        price_label: 'Giá vé một chiều',
        price_value: '220k - 250k /vé',
        cta_text: 'Đặt vé xe 🎫',
        contact_phone: '0981 559 559'
      }
    ]
  },
  {
    id: 4,
    slug: 'fansipan',
    name: 'Sa Pa & Đỉnh Fansipan - Nóc Nhà Đông Dương',
    region: 'Lào Cai',
    description: 'Đỉnh núi cao nhất Việt Nam 3.143m, nơi bạn chạm tay vào đại dương mây bồng bềnh, ngắm đèo Ô Quy Hồ tráng lệ và thung lũng Mường Hoa xanh ngát.',
    cover_image: '/images/fansipan.jpg',
    best_months: 'Tháng 10 - Tháng 4',
    difficulty: 'Thử thách',
    how_to_get_there: 'Tàu hỏa hỏa tốc hoặc xe giường nằm cao tốc Hà Nội - Lào Cai - Sa Pa. Có thể trekking 2N1Đ hoặc đi cáp treo.',
    warnings: 'Nhiệt độ trên đỉnh có thể xuống dưới 0°C vào mùa đông, có sương muối hoặc tuyết rơi, cần mang đồ giữ ấm dày.',
    avg_budget: '2.000.000 - 3.200.000 VNĐ / người',
    is_featured: true,
    elevation: '3.143m',
    cloud_chance: '90%',
    places: [
      {
        id: 401,
        name: 'Quần Thể Cáp Treo & Đỉnh Fansipan 3.143m',
        category: 'trekking',
        category_name: 'Chinh Phục Đỉnh Cao',
        category_icon: '🏔️',
        rating: 4.9,
        review_count: '1.800+',
        location_tag: 'Ga Cáp Treo Mường Hoa',
        highlight_tag: 'Nóc nhà Đông Dương',
        image: '/images/fansipan.jpg',
        description: 'Tuyến cáp treo 3 dây kỷ lục thế giới đưa bạn xuyên qua mây ngàn lên chóp inox 3.143m ngắm toàn cảnh dãy Hoàng Liên Sơn hùng vĩ.',
        price_label: 'Vé cáp treo khứ hồi',
        price_value: '850k /người lớn',
        cta_text: 'Đặt vé cáp 🎫',
        contact_phone: '0981 222 444'
      },
      {
        id: 402,
        name: 'Viettrekking Coffee Sa Pa',
        category: 'cafe',
        category_name: 'Cà Phê Biển Mây',
        category_icon: '☕',
        rating: 4.8,
        review_count: '1.100+',
        location_tag: '33 Hoàng Liên, Sa Pa',
        highlight_tag: 'Tàu hỏa mây ngàn',
        image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
        description: 'Quán cà phê góc săn mây triệu view nhìn thẳng sang dãy Hoàng Liên và tuyến tàu hỏa leo núi đỏ rực băng qua thung lũng.',
        price_label: 'Đồ uống & Trà ấm',
        price_value: '50k - 80k /món',
        cta_text: 'Đường đi 🗺️',
        contact_phone: '0979 555 333'
      },
      {
        id: 403,
        name: 'Nhà Hàng A Phủ Sa Pa',
        category: 'eat',
        category_name: 'Ẩm Thực Tây Bắc',
        category_icon: '🍲',
        rating: 4.8,
        review_count: '890+',
        location_tag: '15 Fansipan, Sa Pa',
        highlight_tag: 'Thắng cố & Cá hồi',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        description: 'Địa chỉ thưởng thức nồi lẩu cá tầm chua cay nóng hổi, thịt lợn bản cắp nách nướng than hoa, gà đen hầm nấm linh chi nức tiếng.',
        price_label: 'Chi phí bình quân',
        price_value: '150k - 250k /người',
        cta_text: 'Xem Menu 📖',
        contact_phone: '0988 666 444'
      },
      {
        id: 404,
        name: 'Eco Palms House Sapa',
        category: 'stay',
        category_name: 'Bungalow Mường Hoa',
        category_icon: '🏨',
        rating: 4.9,
        review_count: '420+',
        location_tag: 'Bản Lao Chải',
        highlight_tag: 'Mái tranh ruộng lúa',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'Khu nghỉ dưỡng nhà gỗ mái tranh mộc mạc bên triền ruộng bậc thang, view ban công nhìn thẳng biển mây và thung lũng Mường Hoa.',
        price_label: 'Giá phòng bungalow',
        price_value: '800k - 1.600k /đêm',
        cta_text: 'Chi tiết →',
        contact_phone: '0912 333 777'
      },
      {
        id: 405,
        name: 'Cổng Trời & Đèo Ô Quy Hồ',
        category: 'checkin',
        category_name: 'Vua Đèo Tây Bắc',
        category_icon: '📸',
        rating: 4.9,
        review_count: '1.400+',
        location_tag: 'Hoàng Liên Sơn',
        highlight_tag: 'Hoàng hôn lửa đỏ',
        image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        description: 'Một trong tứ đại đỉnh đèo hiểm trở và ngoạn mục nhất, nơi chiêm ngưỡng khoảnh khắc hoàng hôn rực rỡ nhất dải đất vùng cao.',
        price_label: 'Vé Cổng Trời',
        price_value: '80k /vé',
        cta_text: 'Định vị Map 🧭',
        contact_phone: 'Ban quản lý'
      },
      {
        id: 406,
        name: 'Tắm Lá Thuốc Dao Đỏ Tả Phìn',
        category: 'trekking',
        category_name: 'Trị Liệu Thảo Dược',
        category_icon: '🌿',
        rating: 4.8,
        review_count: '530+',
        location_tag: 'Bản Tả Phìn',
        highlight_tag: '100+ vị thuốc rừng',
        image: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80',
        description: 'Ngâm mình trong thùng gỗ pơ-mu với nước lá thuốc gia truyền của người Dao Đỏ, xua tan hoàn toàn mệt mỏi sau chuyến leo núi.',
        price_label: 'Dịch vụ tắm lá',
        price_value: '100k - 150k /lần',
        cta_text: 'Đăng ký 🌿',
        contact_phone: '0977 888 222'
      }
    ]
  },
  {
    id: 5,
    slug: 'mu-cang-chai',
    name: 'Mù Cang Chải - Tuyệt Tác Ruộng Bậc Thang',
    region: 'Yên Bái',
    description: 'Di tích danh thắng quốc gia đặc biệt với Đồi Mâm Xôi La Pán Tẩn, Đồi Móng Ngựa Sáng Nhù và đèo Khau Phạ - một trong tứ đại đỉnh đèo Tây Bắc.',
    cover_image: '/images/terraces.jpg',
    best_months: 'Tháng 5 - 6 (Mùa nước đổ) & Tháng 9 - 10 (Mùa lúa chín)',
    difficulty: 'Dễ',
    how_to_get_there: 'Xe khách từ Hà Nội theo QL32 qua Nghĩa Lộ vượt đèo Khau Phạ đến Mù Cang Chải.',
    warnings: 'Đường lên đồi Mâm Xôi dốc đứng trơn trượt mùa mưa, nên thuê xe ôm của người H\'Mông địa phương.',
    avg_budget: '1.500.000 - 2.200.000 VNĐ / người',
    is_featured: true,
    elevation: '1.750m',
    cloud_chance: '85%',
    places: [
      {
        id: 501,
        name: 'Đồi Mâm Xôi La Pán Tẩn',
        category: 'checkin',
        category_name: 'Biểu Tượng Mùa Vàng',
        category_icon: '🌾',
        rating: 4.9,
        review_count: '1.300+',
        location_tag: 'Bản Hán Xung',
        highlight_tag: 'Tuyệt tác bậc thang',
        image: '/images/terraces.jpg',
        description: 'Đồi ruộng bậc thang hình tròn đều đặn tựa mâm xôi dâng trời, rực vàng óng ả vào tháng 9-10 mỗi năm.',
        price_label: 'Vé tham quan',
        price_value: '20k /vé',
        cta_text: 'Định vị Map 🧭',
        contact_phone: '0978 444 555'
      },
      {
        id: 502,
        name: 'Bay Dù Lượn Đèo Khau Phạ',
        category: 'trekking',
        category_name: 'Hoạt Động Cảm Giác Mạnh',
        category_icon: '🪂',
        rating: 4.9,
        review_count: '480+',
        location_tag: 'Đỉnh Đèo Khau Phạ',
        highlight_tag: 'Bay trên mùa vàng',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        description: 'Bay lượn cùng phi công chuyên nghiệp ngắm toàn cảnh thung lũng Lìm Mông lúa chín từ độ cao 1.200m giữa trời mây.',
        price_label: 'Gói bay dù lượn',
        price_value: '1.800k - 2.200k /lần',
        cta_text: 'Đặt lịch bay 🪂',
        contact_phone: '0989 123 456'
      },
      {
        id: 503,
        name: 'Đồi Móng Ngựa Sáng Nhù',
        category: 'checkin',
        category_name: 'Tọa Độ Sunset',
        category_icon: '📸',
        rating: 4.8,
        review_count: '620+',
        location_tag: 'Bản Sáng Nhù',
        highlight_tag: 'Hoàng hôn bậc thang',
        image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        description: 'Ruộng bậc thang uốn lượn hình móng ngựa ngoạn mục, nơi hàng trăm nhiếp ảnh gia săn ánh hoàng hôn nhuộm vàng sóng lúa.',
        price_label: 'Phí vào chụp ảnh',
        price_value: '20k /vé',
        cta_text: 'Đường đi 🗺️',
        contact_phone: 'Bản địa'
      },
      {
        id: 504,
        name: 'Hello Mu Cang Chai Homestay',
        category: 'stay',
        category_name: 'Homestay View Lúa',
        category_icon: '🏨',
        rating: 4.8,
        review_count: '310+',
        location_tag: 'La Pán Tẩn',
        highlight_tag: 'View triệu đô',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'Homestay nằm nép mình bên triền đồi ngắm trọn biển lúa bậc thang, phục vụ lợn bản nướng và xôi ngũ sắc thơm dẻo.',
        price_label: 'Giá phòng',
        price_value: '250k - 600k /đêm',
        cta_text: 'Chi tiết →',
        contact_phone: '0972 555 888'
      },
      {
        id: 505,
        name: 'Nhà Hàng Cơm Lam Gà Nướng Suối Mơ',
        category: 'eat',
        category_name: 'Ẩm Thực Bản Địa',
        category_icon: '🍲',
        rating: 4.7,
        review_count: '390+',
        location_tag: 'Thị trấn Mù Cang Chải',
        highlight_tag: 'Gà nướng than củi',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        description: 'Gà đồi nướng than củi vàng giòn chấm muối tiêu chanh hạt dổi, ăn cùng cơm lam nếp nương Tú Lệ thơm nức dẻo bùi.',
        price_label: 'Chi phí bình quân',
        price_value: '~130k /người',
        cta_text: 'Xem Menu 📖',
        contact_phone: '0916 444 333'
      }
    ]
  },
  {
    id: 6,
    slug: 'thac-ban-gioc',
    name: 'Thác Bản Giốc & Trùng Khánh - Dải Lụa Trắng Non Nước',
    region: 'Cao Bằng',
    description: 'Thác nước tự nhiên lớn nhất Đông Nam Á với các tầng thác tung bọt trắng xóa trên dòng sông Quây Sơn xanh biếc, cùng động Ngườm Ngao và Núi Mắt Thần kỳ vĩ.',
    cover_image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    best_months: 'Tháng 8 - Tháng 11',
    difficulty: 'Dễ',
    how_to_get_there: 'Xe khách giường nằm Hà Nội - TP Cao Bằng (~280k), bắt tiếp xe buýt hoặc thuê xe máy tới Trùng Khánh (~80km).',
    warnings: 'Khu vực biên giới, cần mang theo CCCD/Hộ chiếu khi tham quan và đi thuyền trên sông Quây Sơn.',
    avg_budget: '1.800.000 - 2.600.000 VNĐ / người',
    is_featured: true,
    elevation: '850m',
    cloud_chance: '75%',
    places: [
      {
        id: 601,
        name: 'Thác Bản Giốc & Bè Mãng Sông Quây Sơn',
        category: 'checkin',
        category_name: 'Kỳ Quan Nước Non',
        category_icon: '💦',
        rating: 4.9,
        review_count: '1.600+',
        location_tag: 'Đàm Thủy, Trùng Khánh',
        highlight_tag: 'Thác lớn nhất ĐNA',
        image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
        description: 'Tận mắt chiêm ngưỡng dòng thác 3 tầng cuồn cuộn đổ bọt trắng xóa, đi bè tre áp sát chân thác để cảm nhận làn bụi nước mát lạnh.',
        price_label: 'Vé thác & đi bè',
        price_value: '45k - 50k /người',
        cta_text: 'Định vị Map 🧭',
        contact_phone: '0981 777 333'
      },
      {
        id: 602,
        name: 'Động Ngườm Ngao',
        category: 'checkin',
        category_name: 'Hang Động Kỳ Vĩ',
        category_icon: '🏛️',
        rating: 4.8,
        review_count: '720+',
        location_tag: 'Bản Gun, Đàm Thủy',
        highlight_tag: 'Búp sen đá vôi',
        image: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80',
        description: 'Hang động đá vôi dài hơn 2.000m với kiệt tác búp sen đá úp ngược và những dải nhũ lung linh huyền ảo được thiên nhiên tạo tác triệu năm.',
        price_label: 'Vé tham quan động',
        price_value: '45k /vé',
        cta_text: 'Khám phá 🏛️',
        contact_phone: 'Ban quản lý'
      },
      {
        id: 603,
        name: 'Núi Mắt Thần (Tuyệt Tình Cốc)',
        category: 'stay',
        category_name: 'Cắm Trại Thảo Nguyên',
        category_icon: '⛺',
        rating: 4.9,
        review_count: '650+',
        location_tag: 'Quốc Toản, Trà Lĩnh',
        highlight_tag: 'Núi Thủng kỳ bí',
        image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
        description: 'Thung lũng cỏ xanh mướt bên hồ nước màu ngọc bích phẳng lặng, nơi có ngọn núi thủng độc nhất vô nhị lý tưởng để cắm trại BBQ.',
        price_label: 'Phí vào cắm trại',
        price_value: 'Miễn phí',
        cta_text: 'Đặt lều ⛺',
        contact_phone: 'Bản địa'
      },
      {
        id: 604,
        name: 'Quán Phở Vịt Quay 7 Vị Cao Bằng',
        category: 'eat',
        category_name: 'Đặc Sản Trứ Danh',
        category_icon: '🍲',
        rating: 4.8,
        review_count: '510+',
        location_tag: 'Phố Cũ, TP Cao Bằng',
        highlight_tag: 'Vịt quay da giòn',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        description: 'Vịt quay thơm phức ướp 7 vị thảo quả truyền thống, da bóng giòn rụm chấm nước sốt đậm đà, ăn kèm bánh phở tươi tráng tay.',
        price_label: 'Chi phí món ăn',
        price_value: '35k - 50k /bát',
        cta_text: 'Xem Menu 📖',
        contact_phone: '0973 111 888'
      },
      {
        id: 605,
        name: 'Sài Gòn - Bản Giốc Resort',
        category: 'stay',
        category_name: 'Resort Cao Cấp',
        category_icon: '🏨',
        rating: 4.7,
        review_count: '280+',
        location_tag: 'Xã Đàm Thủy',
        highlight_tag: 'View thác nước',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'Khu nghỉ dưỡng 4 sao view hướng trọn thác Bản Giốc, khuôn viên xanh mát với nhà hàng đặc sản và dịch vụ chăm sóc chu đáo.',
        price_label: 'Giá phòng',
        price_value: '950k - 1.800k /đêm',
        cta_text: 'Chi tiết →',
        contact_phone: '0982 333 999'
      }
    ]
  },
  {
    id: 7,
    slug: 'y-ty',
    name: 'Y Tý & Lảo Thẩn - Xứ Sở Sương Mù & Nhà Trình Tường',
    region: 'Lào Cai',
    description: 'Xứ sở sương mù biên giới với những ngôi nhà nấm trình tường của người Hà Nhì nép mình bên triền núi, biển mây Ngải Thầu Thượng và đỉnh Lảo Thẩn 2.860m.',
    cover_image: '/images/yty.jpg',
    best_months: 'Tháng 9 - Tháng 4',
    difficulty: 'Trung bình',
    how_to_get_there: 'Tàu hoặc xe khách lên TP Lào Cai, thuê xe máy đi qua Bát Xát - Bản Vược lên Y Tý.',
    warnings: 'Đoạn đường Dền Sáng - Y Tý nhiều đá dăm trơn trượt khi sương mù hoặc mưa phùn.',
    avg_budget: '1.600.000 - 2.400.000 VNĐ / người',
    is_featured: true,
    elevation: '2.860m',
    cloud_chance: '92%',
    places: [
      {
        id: 701,
        name: 'Trekking Đỉnh Lảo Thẩn (2.860m)',
        category: 'trekking',
        category_name: 'Hoạt Động & Trekking',
        category_icon: '🥾',
        rating: 4.9,
        review_count: '820+',
        location_tag: 'Bản Phìn Hồ',
        highlight_tag: 'Mỏm đá câu cá',
        image: '/images/yty.jpg',
        description: 'Nóc nhà Y Tý, cung trekking ngắm hoàng hôn và bình minh biển mây được mệnh danh là đẹp và dễ đi nhất miền Bắc.',
        price_label: 'Gói tour porter',
        price_value: '1.200k - 1.600k /người',
        cta_text: 'Lộ trình Trekking 🥾',
        contact_phone: '0987 111 555'
      },
      {
        id: 702,
        name: 'Công Viên & Bản Choản Thèn',
        category: 'checkin',
        category_name: 'Văn Hóa Bản Địa',
        category_icon: '🍃',
        rating: 4.8,
        review_count: '490+',
        location_tag: 'Bản Choản Thèn',
        highlight_tag: 'Nhà nấm cổ kính',
        image: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80',
        description: 'Ngắm nhìn hai cây thông cô đơn đứng sừng sững bên triền dốc và những ngôi nhà trình tường bằng đất hình nấm của người Hà Nhì.',
        price_label: 'Vé tham quan',
        price_value: 'Miễn phí',
        cta_text: 'Định vị Map 🧭',
        contact_phone: 'Bản địa'
      },
      {
        id: 703,
        name: 'Ngải Thầu Thượng Viewpoint',
        category: 'cafe',
        category_name: 'Tọa Độ Săn Mây',
        category_icon: '☁️',
        rating: 4.9,
        review_count: '570+',
        location_tag: 'Độ cao 2.100m',
        highlight_tag: 'Sóng mây cuồn cuộn',
        image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        description: 'Điểm săn mây luồn đẹp ngỡ ngàng khi biển mây từ thung lũng tràn qua những rặng cây sa mộc thẳng tắp.',
        price_label: 'Phí vào cửa',
        price_value: 'Miễn phí',
        cta_text: 'Đường đi 🗺️',
        contact_phone: 'Bản địa'
      },
      {
        id: 704,
        name: 'A Hờ Homestay Y Tý',
        category: 'stay',
        category_name: 'Homestay View Mây',
        category_icon: '🏨',
        rating: 4.7,
        review_count: '340+',
        location_tag: 'Thôn Ngải Trồ',
        highlight_tag: 'Cơm canh rau rừng',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'Homestay ấm cúng của người Mông với view ngắm mây tràn thung lũng, thưởng thức lẩu gà đen và rượu Sim San men lá trứ danh.',
        price_label: 'Giá phòng',
        price_value: '200k - 500k /đêm',
        cta_text: 'Chi tiết →',
        contact_phone: '0975 888 111'
      }
    ]
  },
  {
    id: 8,
    slug: 'binh-lieu',
    name: 'Bình Liêu - "Sống Lưng Khủng Long" Miền Cỏ Lau',
    region: 'Quảng Ninh',
    description: 'Được ví như "Sa Pa thu nhỏ" của Quảng Ninh với con đường tuần tra biên giới uốn lượn trên sống núi, cột mốc 1305 và những triền đồi ngập tràn bông cỏ lau trắng muốt.',
    cover_image: '/images/pass_road.jpg',
    best_months: 'Tháng 10 - Tháng 12 (Mùa cỏ lau)',
    difficulty: 'Dễ',
    how_to_get_there: 'Xe khách từ Hà Nội đến Tiên Yên hoặc Bình Liêu theo cao tốc Hà Nội - Hải Phòng - Hạ Long - Vân Đồn.',
    warnings: 'Đoạn bậc thang lên mốc 1305 khá dốc và dài khoảng 2km, nên mang giày thể thao bám tốt và nước uống.',
    avg_budget: '1.200.000 - 1.800.000 VNĐ / người',
    is_featured: false,
    elevation: '1.429m',
    cloud_chance: '70%',
    places: [
      {
        id: 801,
        name: 'Cột Mốc 1305 & Sống Lưng Khủng Long',
        category: 'trekking',
        category_name: 'Hoạt Động & Trekking',
        category_icon: '🥾',
        rating: 4.9,
        review_count: '980+',
        location_tag: 'Đồng Văn, Bình Liêu',
        highlight_tag: 'Cung đường sống núi',
        image: '/images/pass_road.jpg',
        description: 'Cung đường bê tông dài 2km uốn lượn trên đỉnh sống núi giữa hai sườn dốc đứng ngút ngàn bông cỏ lau trắng muốt.',
        price_label: 'Vé tham quan',
        price_value: 'Miễn phí',
        cta_text: 'Định vị Map 🧭',
        contact_phone: 'Biên phòng'
      },
      {
        id: 802,
        name: 'Cột Mốc 1297 (Thiên Đường Cỏ Lau)',
        category: 'checkin',
        category_name: 'Tọa Độ Check-in',
        category_icon: '📸',
        rating: 4.8,
        review_count: '640+',
        location_tag: 'Đình Lập - Bình Liêu',
        highlight_tag: 'Bạt ngàn hoa lau',
        image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        description: 'Triền đồi ngập tràn hoa cỏ lau trắng bay bồng bềnh trong gió thu đông, địa điểm chụp ảnh cưới và check-in đẹp mê mẩn.',
        price_label: 'Vé tham quan',
        price_value: 'Miễn phí',
        cta_text: 'Đường đi 🗺️',
        contact_phone: 'Bản địa'
      },
      {
        id: 803,
        name: 'Quán Gà Đồi & Cá Suối Tiên Yên',
        category: 'eat',
        category_name: 'Ẩm Thực Đặc Sản',
        category_icon: '🍲',
        rating: 4.7,
        review_count: '380+',
        location_tag: 'Thị trấn Bình Liêu',
        highlight_tag: 'Gà Tiên Yên da vàng',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        description: 'Thưởng thức món gà đồi Tiên Yên da giòn ngậy thịt ngọt lịm chấm muối ớt gừng, xôi ngũ sắc và miến dong Bình Liêu xào lòng gà.',
        price_label: 'Chi phí bình quân',
        price_value: '~120k /người',
        cta_text: 'Xem Menu 📖',
        contact_phone: '0974 666 222'
      }
    ]
  },
  {
    id: 9,
    slug: 'pu-luong',
    name: 'Pù Luông - Ốc Đảo Xanh Đại Ngàn Ruộng Bậc Thang',
    region: 'Thanh Hóa',
    description: 'Khu bảo tồn thiên nhiên Pù Luông với thung lũng ruộng bậc thang xanh mướt ngút ngàn, guồng nước Bản Cốc, suối Hiêu và bản Đôn bình yên giữa núi đá vôi.',
    cover_image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    best_months: 'Tháng 5 - 6 & Tháng 9 - 10',
    difficulty: 'Dễ',
    how_to_get_there: 'Xe Limousine Hà Nội - Pù Luông qua QL6 đến ngã ba Bản Lác rẽ sang QL15C (khoảng 4 giờ).',
    warnings: 'Nên chuẩn bị thuốc chống muỗi và côn trùng khi đi dạo trong các bản làng rừng nguyên sinh.',
    avg_budget: '1.300.000 - 2.000.000 VNĐ / người',
    is_featured: false,
    elevation: '1.700m',
    cloud_chance: '76%',
    places: [
      {
        id: 901,
        name: 'Puluong Retreat & Ruộng Bậc Thang Bản Đôn',
        category: 'stay',
        category_name: 'Resort Bể Bơi Vô Cực',
        category_icon: '🏨',
        rating: 4.9,
        review_count: '760+',
        location_tag: 'Bản Đôn, Pù Luông',
        highlight_tag: 'Bể bơi view thung lũng',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'Bể bơi vô cực nhìn thẳng ra biển lúa bậc thang ngút ngàn, các bungalow bằng gỗ cọ thân thiện với thiên nhiên thanh bình.',
        price_label: 'Giá phòng',
        price_value: '800k - 2.200k /đêm',
        cta_text: 'Chi tiết →',
        contact_phone: '0969 555 111'
      },
      {
        id: 902,
        name: 'Guồng Nước Khổng Lồ Bản Cốc',
        category: 'checkin',
        category_name: 'Di Sản Nông Nghiệp',
        category_icon: '🍃',
        rating: 4.8,
        review_count: '420+',
        location_tag: 'Suối Chàm, Bản Cốc',
        highlight_tag: 'Chèo bè tre thư giãn',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        description: 'Những cỗ guồng nước khổng lồ bằng tre nứa quay đều đặn bên dòng suối trong vắt, chèo bè tre xuôi dòng tận hưởng không khí mát lành.',
        price_label: 'Chèo bè tre suối',
        price_value: '50k /người',
        cta_text: 'Định vị Map 🧭',
        contact_phone: 'Bản địa'
      },
      {
        id: 903,
        name: 'Ẩm Thực Vịt Cổ Lũng Pù Luông',
        category: 'eat',
        category_name: 'Đặc Sản Tiến Vua',
        category_icon: '🍲',
        rating: 4.8,
        review_count: '530+',
        location_tag: 'Bản Đôn & Cổ Lũng',
        highlight_tag: 'Vịt nướng mắc khén',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        description: 'Giống vịt cổ ngắn xương nhỏ thịt thơm chắc nướng than hoa thơm lừng hạt dổi mắc khén, ăn cùng canh đắng và măng rừng xào.',
        price_label: 'Chi phí bình quân',
        price_value: '~140k /người',
        cta_text: 'Xem Menu 📖',
        contact_phone: '0978 222 333'
      }
    ]
  },
  {
    id: 10,
    slug: 'ho-ba-be',
    name: 'Hồ Ba Bể - Viên Ngọc Xanh Vườn Quốc Gia',
    region: 'Bắc Kạn',
    description: 'Hồ nước ngọt tự nhiên trên núi đá vôi lớn nhất Việt Nam, nơi bạn có thể chèo thuyền kayak lướt trên mặt nước êm đềm xanh như ngọc qua Động Puông và Thác Đầu Đẳng.',
    cover_image: 'https://images.unsplash.com/photo-1439853941329-a99203348b78?auto=format&fit=crop&w=1200&q=80',
    best_months: 'Quanh năm (Đẹp nhất mùa Thu - Đông)',
    difficulty: 'Dễ',
    how_to_get_there: 'Xe khách từ bến Mỹ Đình Hà Nội theo cao tốc Hà Nội - Thái Nguyên - Chợ Mới đến Ba Bể.',
    warnings: 'Chú ý mặc áo phao cứu sinh khi tham gia các hoạt động chèo kayak hoặc đi xuồng máy trên hồ.',
    avg_budget: '1.400.000 - 2.100.000 VNĐ / người',
    is_featured: false,
    elevation: '600m',
    cloud_chance: '72%',
    places: [
      {
        id: 1001,
        name: 'Chèo Xuồng & Kayak Hồ Ba Bể',
        category: 'trekking',
        category_name: 'Hoạt Động Sông Hồ',
        category_icon: '🛶',
        rating: 4.9,
        review_count: '610+',
        location_tag: 'Bến Buốc Lốm',
        highlight_tag: 'Hồ nước trong như ngọc',
        image: 'https://images.unsplash.com/photo-1439853941329-a99203348b78?auto=format&fit=crop&w=800&q=80',
        description: 'Lướt thuyền kayak trên mặt hồ phẳng lặng như gương qua đảo Bà Góa, Đền An Mạ và vách đá vôi phủ rêu phong cổ thụ.',
        price_label: 'Thuê thuyền kayak',
        price_value: '100k - 150k /giờ',
        cta_text: 'Thuê kayak 🛶',
        contact_phone: '0985 444 666'
      },
      {
        id: 1002,
        name: 'Động Puông & Thác Đầu Đẳng',
        category: 'checkin',
        category_name: 'Kỳ Quan Địa Chất',
        category_icon: '🏛️',
        rating: 4.8,
        review_count: '430+',
        location_tag: 'Dòng sông Năng',
        highlight_tag: 'Hang luồn khổng lồ',
        image: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80',
        description: 'Hang động đá vôi khổng lồ cao hơn 30m cho thuyền xuyên qua lòng núi, nơi cư ngụ của hàng vạn con dơi và nhũ đá kỳ ảo.',
        price_label: 'Vé tham quan',
        price_value: '30k /vé',
        cta_text: 'Khám phá 🏛️',
        contact_phone: 'Ban quản lý'
      },
      {
        id: 1003,
        name: 'Homestay Bản Pác Ngòi',
        category: 'stay',
        category_name: 'Nhà Sàn Người Tày',
        category_icon: '🏨',
        rating: 4.8,
        review_count: '370+',
        location_tag: 'Bản Pác Ngòi',
        highlight_tag: 'Ven bờ hồ xanh ngát',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'Nghỉ đêm trong những nếp nhà sàn gỗ cổ truyền thống ven hồ, thưởng thức cá mương nướng than hoa và tôm chua Ba Bể thơm ngọt.',
        price_label: 'Giá phòng',
        price_value: '200k - 500k /đêm',
        cta_text: 'Chi tiết →',
        contact_phone: '0979 222 777'
      }
    ]
  }
];

export const destinationService = {
  async getAll(params = {}) {
    let combined = [...CURATED_NORTHERN_DESTINATIONS];
    try {
      const response = await api.get('/destinations', { params });
      const apiList = response?.data?.data || (Array.isArray(response.data) ? response.data : []);
      if (apiList.length > 0) {
        // Merge API items with curated ones, avoiding duplicates by id or slug
        const apiSlugs = new Set(apiList.map((d) => d.slug || String(d.id)));
        const nonDuplicateCurated = CURATED_NORTHERN_DESTINATIONS.filter(
          (d) => !apiSlugs.has(d.slug) && !apiSlugs.has(String(d.id))
        );
        combined = [...apiList, ...nonDuplicateCurated];
      }
    } catch (err) {
      console.warn('API /destinations unavailable, using curated Northern destinations:', err.message);
    }

    let filtered = combined;
    if (params.search) {
      const q = params.search.toLowerCase();
      filtered = filtered.filter((d) =>
        (d.name && d.name.toLowerCase().includes(q)) ||
        (d.description && d.description.toLowerCase().includes(q)) ||
        (d.region && d.region.toLowerCase().includes(q))
      );
    }
    if (params.featured === 'true') {
      filtered = filtered.filter((d) => d.is_featured);
    }
    return { data: filtered };
  },

  async getById(id) {
    try {
      const response = await api.get(`/destinations/${id}`);
      if (response?.data) {
        // If API returns data, merge or fallback to curated places if empty
        const apiData = response.data;
        const curatedMatch = CURATED_NORTHERN_DESTINATIONS.find(
          (d) => String(d.id) === String(id) || d.slug === String(id) || d.slug === apiData.slug
        );
        if (curatedMatch && (!apiData.places || apiData.places.length === 0)) {
          return { data: { ...curatedMatch, ...apiData, places: curatedMatch.places } };
        }
        return { data: response.data?.data || response.data };
      }
    } catch (err) {
      console.warn(`API /destinations/${id} not found, searching curated Northern list`);
    }
    const found = CURATED_NORTHERN_DESTINATIONS.find(
      (d) => String(d.id) === String(id) || d.slug === String(id)
    );
    if (found) return { data: found };
    return { data: CURATED_NORTHERN_DESTINATIONS[0] };
  },

  async create(data) {
    const response = await api.post('/destinations', data);
    return response.data;
  },

  async update(id, data) {
    const response = await api.put(`/destinations/${id}`, data);
    return response.data;
  },

  async delete(id) {
    const response = await api.delete(`/destinations/${id}`);
    return response.data;
  },
};


